version: '3.9'
services:
  nxtcloud:
    image: nextcloud:stable
    volumes:
      - ./nxtcloud-data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - POSTGRES_DB=nxtcloud-db
      - POSTGRES_USER=nxtcloud-user
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=cache
      - OBJECTSTORE_S3_HOST=object-storage      


  postgres:
    image: postgres:15-bullseye
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  object-storage:
    image: minio:latest
    volumes:
      - ./minio-data:/data

  cache:
    image: redis:alpine
    volumes:
      - ./redis-data:/data


networks:
  nxtcloud:
    name: nxtcloud-network
    driver: bridge
    external: true
